### ISSUE TITLE
server crash when death by wraith

### ISSUE THREAD

**Issue by kuba26038** [Alexthw46/Eidolon-Repraised#26]
not really sure what causes it, but this mod was mentioned, so here you go

i was playing normally, but when i died to a wraith, this happened. it didn't happen so when i got killed by zombies or the /kill command

[crash-2023-11-16_14.45.52-server.txt](https://github.com/Alexthw46/Eidolon-Repraised/files/13382146/crash-2023-11-16_14.45.52-server.txt)

**Comment by SiverDX** [comment]
this is on engimatic legacy

https://github.com/Aizistral-Studios/Enigmatic-Legacy/issues/451

you had an escape scroll (the one that teleports your items to you when you die) when you were killed by the wraith

```log
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.BlockPos.m_123341_()" because "pos" is null
	at net.minecraft.world.level.Level.m_8055_(Level.java:4041) ~[server-1.19.2-20220805.130853-srg.jar%23635!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:redirector-forge.mixins.json:net.minecraft.world.level.LevelMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:strawgolem.forge.mixins.json:GrowthMixin,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:blockswap.mixins.json:MixinLevel,pl:mixin:A}
	at com.aizistral.enigmaticlegacy.handlers.EnigmaticEventHandler.onLivingDropsLowest(EnigmaticEventHandler.java:2443) ~[EnigmaticLegacy-2.26.5.jar%23451!/:2.26.5] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at com.aizistral.enigmaticlegacy.handlers.__EnigmaticEventHandler_onLivingDropsLowest_LivingDropsEvent.invoke(.dynamic) ~[EnigmaticLegacy-2.26.5.jar%23451!/:2.26.5] {re:classloading,pl:eventbus:B}
```
