### ISSUE TITLE
Game Crashes when Reading about Altar Lightning

### ISSUE THREAD

**Issue by KakashoLin** [Alexthw46/Eidolon-Repraised#64]
When you try and open the section about altar lighting the game crashes with this message.

The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "elucent.eidolon.api.altar.AltarEntry.getPower()" because "entry" is null

**Comment by x13x54** [comment]
I just ran into this issue too!
Modpack used was ATM9
Here is the stacktrace:
```[28Jul2024 07:37:25.094] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:978) ~[client-1.20.1-20230612.114412-srg.jar%23998!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23998!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23998!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.20.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.20.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.20.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "elucent.eidolon.api.altar.AltarEntry.getPower()" because "entry" is null
	at elucent.eidolon.codex.ListPage.render(ListPage.java:60) ~[eidolon_repraised-1.20.1-0.3.8.10.jar%23703!/:1.20.1-0.3.8.10]
	at elucent.eidolon.codex.Page.fullRender(Page.java:87) ~[eidolon_repraised-1.20.1-0.3.8.10.jar%23703!/:1.20.1-0.3.8.10]
	at elucent.eidolon.codex.CodexGui.m_88315_(CodexGui.java:156) ~[eidolon_repraised-1.20.1-0.3.8.10.jar%23703!/:1.20.1-0.3.8.10]
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23998!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.2.20-universal.jar%231003!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.2.20-universal.jar%231003!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23998!/:?]
	... 16 more

**Comment by Alexthw46** [comment]
assumed it was fixed because it didn't happen in dev, but seems to reliably happen in ATM specifically. might be that they do something custom...

**Comment by Alexthw46** [comment]
additional lanterns replaces the vanilla lantern and messes up with the page apparently

**Comment by x13x54** [comment]
well that explains it.
I've found the information that i was looking for by going through the repo, so for anyone needing to read that page, here it is:
https://github.com/Alexthw46/Eidolon-Repraised/blob/1.20.1-Neo/src/main/java/elucent/eidolon/registries/AltarEntries.java
