### ISSUE TITLE
apotheosis update broke the mod

### ISSUE THREAD

**Issue by Xplodin** [Alexthw46/Eidolon-Repraised#67]
Failed to create mod instance. ModID: eidolon, class elucent.eidolon.Eidolon
java.lang.NoClassDefFoundError: dev/shadowsoffire/apotheosis/adventure/affix/socket/gem/bonus/GemBonus
	at elucent.eidolon.compat.apotheosis.TrackingAffix.lambda$static$1(TrackingAffix.java:20) ~[eidolon_repraised-1.20.1-0.3.8.10.jar%23950!/:1.20.1-0.3.8.10]
	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-6.0.8.jar%23114!/:?]
	at elucent.eidolon.compat.apotheosis.TrackingAffix.<clinit>(TrackingAffix.java:20) ~[eidolon_repraised-1.20.1-0.3.8.10.jar%23950!/:1.20.1-0.3.8.10]
	at elucent.eidolon.compat.apotheosis.Apotheosis.initialize(Apotheosis.java:44) ~[eidolon_repraised-1.20.1-0.3.8.10.jar%23950!/:1.20.1-0.3.8.10]
	at elucent.eidolon.compat.CompatHandler.lambda$initialize$0(CompatHandler.java:19) ~[eidolon_repraised-1.20.1-0.3.8.10.jar%23950!/:1.20.1-0.3.8.10]
	at java.util.Map.forEach(Map.java:713) ~[?:?]
	at elucent.eidolon.compat.CompatHandler.initialize(CompatHandler.java:17) ~[eidolon_repraised-1.20.1-0.3.8.10.jar%23950!/:1.20.1-0.3.8.10]
	at elucent.eidolon.Eidolon.<init>(Eidolon.java:96) ~[eidolon_repraised-1.20.1-0.3.8.10.jar%23950!/:1.20.1-0.3.8.10]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.19.jar%231364!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.19.jar%231363!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ClassNotFoundException: dev.shadowsoffire.apotheosis.adventure.affix.socket.gem.bonus.GemBonus
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 22 more

crashes on boot

**Comment by Maxi90909** [comment]
Was about to also report this issue. Passive skill tree has a similar issue.
![Screenshot (44)](https://github.com/Alexthw46/Eidolon-Repraised/assets/76815835/7fbe5711-8603-4a7e-992b-6ec943b1e0d3)

**Comment by EliminatorXIX** [comment]
This mod, passive skill tree and the apotheosis + better combat mod all need to update their compatibility
