### ISSUE TITLE
Conflict with Corails tombstone due to checking potions before mob is fully <init>ed

### ISSUE THREAD

**Issue by ChiefArug** [Alexthw46/Eidolon-Repraised#9]
Corails Tombstone checks a mobs type in the attach capabilities event. [Eidolon mixins to there](https://github.com/Alexthw46/Eidolon-Repraised/blob/1.19.2/src/main/java/elucent/eidolon/mixin/LivingEntityMixin.java#L18-L23) to add a check for the undeath effect, which causes `Cannot invoke "java.util.Map.containsKey(Object)" because "this.activeEffects" is null` when a mob tries to spawn, causing large log spam.

<details>
  <summary>Stacktrace</summary>
  
  ```
[20Oct2023 00:06:34.067] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "java.util.Map.containsKey(Object)" because "this.f_20945_" is null
	Index: 20
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@4471ced9
		2: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@4c313802
		3: ASM: xaero.map.events.Events@503fcf08 worldCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		4: ASM: org.cyclops.cyclopscore.modcompat.capabilities.CapabilityConstructorRegistry$TileEventListener@2a784d49 onTileLoad(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		5: ASM: class com.aetherteam.aether.capability.AetherCapabilities$Registration attachEntityCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		6: ASM: class com.aetherteam.aether.capability.AetherCapabilities$Registration attachWorldCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		7: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@5554c361
		8: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@613d06d2
		9: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@2bf01b2a
		10: ASM: class com.legacy.lost_aether.event.LCEvents onCapabilityAttached(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		11: ASM: com.mrbysco.forcecraft.capabilities.CapabilityAttachHandler@34f55e03 attachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		12: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@6e44c77e
		13: ASM: class com.legacy.structure_gel.core.events.SGCommonEvents$ForgeBus attachEntityCap(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		14: ASM: class com.legacy.structure_gel.core.events.SGCommonEvents$ForgeBus attachLevelCap(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		15: ASM: org.cyclops.cyclopscore.modcompat.capabilities.CapabilityConstructorRegistry$TileEventListener@7cdcefe2 onTileLoad(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		16: ASM: org.cyclops.cyclopscore.modcompat.capabilities.CapabilityConstructorRegistry$ItemStackEventListener@3de8d896 onItemStackLoad(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		17: ASM: org.cyclops.cyclopscore.modcompat.capabilities.CapabilityConstructorRegistry$EntityEventListener@75085651 onEntityLoad(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		18: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onAttachTileCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		19: ASM: class ovh.corail.tombstone.event.EventHandler onAttachItemCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		20: ASM: class ovh.corail.tombstone.event.EventHandler onAttachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		21: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@1df84e1c
		22: ASM: class tv.soaryn.xycraft.core.XyCoreCommon onAttachCapabilitiesToPlayer(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		23: ASM: class tv.soaryn.xycraft.core.XyCoreClient$ForgeBus onAttachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		24: ASM: elucent.eidolon.event.Events@69c71076 attachEntityCaps(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		25: ASM: elucent.eidolon.event.Events@69c71076 attachWorldCaps(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		26: ASM: INSTANCE onEntityConstruction(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		27: ASM: class me.desht.pneumaticcraft.common.thirdparty.computercraft.ComputerCraft attachPeripheralCap(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		28: ASM: me.desht.pneumaticcraft.common.thirdparty.mekanism.Mekanism@2004b727 attachHeatAdapters(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		29: ASM: me.desht.pneumaticcraft.common.thirdparty.mekanism.Mekanism@2004b727 attachRadiationShield(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		30: ASM: class me.desht.pneumaticcraft.common.thirdparty.curios.Curios$CuriosCapabilityListener attachCurioInvTicker(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		31: ASM: class com.hollingsworth.arsnouveau.setup.registry.CapabilityRegistry$EventHandler attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		32: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@14fac0e7
		33: ASM: class sonar.fluxnetworks.register.EventHandler onAttachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		34: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@3f78b019
		35: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@774fffbf
		36: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@2898d7e4
		37: ASM: mods.railcraft.Railcraft@3ddef04e handleAttachItemStackCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		38: ASM: mods.railcraft.Railcraft@3ddef04e handleAttachEntityCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		39: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@6a27d7e8
		40: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@10255acd
		41: ASM: class com.simibubi.create.foundation.events.CommonEvents attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		42: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@189ffd71
		43: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@1f2febf attachEntitiesCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		44: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@1f2febf attachStackCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		45: ASM: com.illusivesoulworks.comforts.common.CapabilitySleepData$CapabilityEvents@15c75b08 onAttachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		46: ASM: mcjty.lib.setup.ModSetup$EventHandler@7f32a48d onEntityConstructing(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		47: ASM: mcjty.rftoolsutility.setup.ForgeEventHandlers@65cb973b onEntityConstructing(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		48: ASM: mcjty.theoneprobe.ForgeEventHandlers@2733b44c onEntityConstructing(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		49: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@76563e71
		50: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@229a3fc4
		51: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@18d3fa68
		52: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@7fc0e876
		53: ASM: org.cyclops.cyclopscore.modcompat.capabilities.CapabilityConstructorRegistry$TileEventListener@4840bd08 onTileLoad(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		54: ASM: com.illusivesoulworks.polymorph.common.CommonEventsListener@7724bf0b attachCapabilitiesPlayer(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		55: ASM: com.illusivesoulworks.polymorph.common.CommonEventsListener@7724bf0b attachCapabilitiesStack(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		56: ASM: com.illusivesoulworks.polymorph.common.CommonEventsListener@7724bf0b attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		57: ASM: mekanism.common.CommonPlayerTracker@b114db5 attachCaps(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		58: ASM: xaero.pac.client.event.ClientEventsForge@6dcee998 worldCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
		59: net.minecraftforge.eventbus.EventBus$$Lambda$1627/0x0000000801372438@38a2e449
java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "this.f_20945_" is null
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_21023_(LivingEntity.java:910)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.handler$zbb000$getMobType(LivingEntity.java:4041)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_6336_(LivingEntity.java)
	at TRANSFORMER/tombstone@8.5.5/ovh.corail.tombstone.helper.EntityHelper.isUndead(EntityHelper.java:317)
	at TRANSFORMER/tombstone@8.5.5/ovh.corail.tombstone.event.EventHandler.onAttachCapability(EventHandler.java:705)
	at TRANSFORMER/tombstone@8.5.5/ovh.corail.tombstone.event.__EventHandler_onAttachCapability_AttachCapabilitiesEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.1.79/net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:634)
	at TRANSFORMER/forge@47.1.79/net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:628)
	at TRANSFORMER/forge@47.1.79/net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:72)
	at TRANSFORMER/forge@47.1.79/net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:67)
	at TRANSFORMER/forge@47.1.79/net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:51)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.<init>(Entity.java:265)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.<init>(LivingEntity.java:233)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Mob.<init>(Mob.java:123)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.PathfinderMob.<init>(PathfinderMob.java:14)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.AgeableMob.<init>(AgeableMob.java:29)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.animal.Animal.<init>(Animal.java:40)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.TamableAnimal.<init>(TamableAnimal.java:28)
	at TRANSFORMER/rats@1.20.1-8.1.2/com.github.alexthe666.rats.server.entity.rat.AbstractRat.<init>(AbstractRat.java:88)
	at TRANSFORMER/rats@1.20.1-8.1.2/com.github.alexthe666.rats.server.entity.rat.DiggingRat.<init>(DiggingRat.java:32)
	at TRANSFORMER/rats@1.20.1-8.1.2/com.github.alexthe666.rats.server.entity.rat.Rat.<init>(Rat.java:63)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:525)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.NaturalSpawner.m_46988_(NaturalSpawner.java:231)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:169)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:118)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:108)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:362)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:316)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)
  ```
</details>

[Log (24MB)](https://github.com/Alexthw46/Eidolon-Repraised/files/13050884/2023-10-20-4.log)

Should just be able to fix this with a null check there.

**Comment by ChiefArug** [comment]
Also would be great if you could prefix your mixin methods with your modid (like `eidolonrepraised$getMobType`), it would of made figuring out this issue much easier.

**Comment by Gbergz** [comment]
Still happens here with version 0.3.5.5 released 3 hours ago.

**Comment by Alexthw46** [comment]
Then it's not a matter of null check the instance, will check if active effects is null then

**Comment by Alexthw46** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/eidolon-repraised try new?

**Comment by Gbergz** [comment]
Works now. Able to boot, able to enter world.
